version: '3.7'
services:
  app:
    build: .
    command: gunicorn woodie_api.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/woodie_api
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
      - DEBUG=0
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
