version: '3.7'
services:
  app:
    build: .
    command: gunicorn woodie_api.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/woodie_api
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
      - SECRET_KEY=@k-wcwj%y(gifn_&x^+^l8)z@68dam4v=e8j_k4t9l%3osk1zx
      - AWS_ACCESS_KEY_ID=AKIAXNEQY35GQSZ3WWFD
      - AWS_SECRET_ACCESS_KEY=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
      - DEBUG=0
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
