# Generated by Django 3.2 on 2021-08-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='subscrever',
            field=models.BooleanField(default=False, verbose_name='Pretendo receber as últimas novidades da Woodi'),
        ),
    ]
