# Generated by Django 3.2 on 2021-10-03 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='comentário',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='contacto_telefónico',
        ),
        migrations.AddField(
            model_name='reservas',
            name='comentario',
            field=models.TextField(blank=True, verbose_name='Comentário'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='contacto_telefonico',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in a valid format.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Contacto telefónico'),
        ),
    ]
