# Generated by Django 3.2 on 2021-08-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservas_subscrever'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colecao',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
