# Generated by Django 3.2 on 2021-04-09 08:35

import colorfield.fields
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to=core.models.recipe_image_file_path)),
                ('main_background', models.ImageField(null=True, upload_to=core.models.recipe_image_file_path)),
                ('text_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
