# Generated by Django 3.2 on 2021-08-06 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_colecao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Coleções',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='colecao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.colecao'),
        ),
    ]
