# Generated by Django 3.2 on 2021-04-10 09:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210410_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.recipe_image_file_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.recipe_image_file_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.recipe_image_file_path),
        ),
        migrations.AlterField(
            model_name='stylesettings',
            name='logo',
            field=models.ImageField(null=True, upload_to=core.models.settings_image),
        ),
        migrations.AlterField(
            model_name='stylesettings',
            name='main_background',
            field=models.ImageField(null=True, upload_to=core.models.settings_image),
        ),
    ]
