# Generated by Django 3.2 on 2021-06-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210410_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='destacar_producto',
            field=models.BooleanField(default=False),
        ),
    ]
