# Generated by Django 3.2 on 2021-06-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_destacar_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=155)),
                ('ultimo_nome', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=255)),
                ('cidade', models.CharField(max_length=155)),
                ('comentario', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='destacar_producto',
            new_name='destacar_produto',
        ),
    ]
